### ISSUE TITLE
Complete the Form (Except Verification)

### ISSUE THREAD

**Issue by malcolm-kee** [malaysianpaygap/website#2]
As 

**a Malaysian employee**, 

I want to 

**submit my salary and job details anonymously** 

so that 

**I can contribute to MGP goal of making workers' salary/benefits more transparent**.

## Technical Details

Add all the fields that are currently available in [the Google form](https://docs.google.com/forms/d/e/1FAIpQLScdcVFgnc8oiwFIT7-54C62Oc2eremwWzK13msSn8c8ifxZOA/viewform) into [SubmitSalaryForm](https://github.com/malaysianpaygap/website/blob/main/src/modules/salary-submission/components/submit-salary-form.tsx) except the verification (to be covered by #4).

**Comment by Ganthology** [comment]
Will commit at least 2 hours starting from tomorrow for this week.

**Comment by Ganthology** [comment]
Done
- Added fields required except Others field
 
Pending
- Add allowOthers prop to Dropdown component
- Add validation to email field

**Comment by Ganthology** [comment]
Will commit at least 1-2 hours for the following days. Hope to complete pending items by this week.

**Comment by Ganthology** [comment]
Done
- Add validation to email field

Pending
- Add allowOthers prop to Dropdown component

**Comment by leeke2** [comment]
We need to add searchable dropdown for industry / job specialisation field. We will give examples of what would fall under each industry, which needs to searchable as well.

**Comment by malcolm-kee** [comment]
@Ganthology please create a PR once it's fully done.

@leeke2 yeah that's part of the plan, tracked by #3
